name: nlp-workshop
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - ujson
    - jsonnet
    - nodejs
    - pandas
    - numpy
    - flask
    - fire
    - torch
    - torchvision
    - fastai
    - allennlp
    - seaborn
    - sentencepiece
    - spacy
    - aiogram
    - tqdm 
    - redis
    - praw
    - python-dotenv
    - docker-compose